[versions]
<<<<<<< HEAD
agp = "8.6.1"
=======
agp = "8.5.2"
>>>>>>> 295aa9b (noyt)
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseFirestore = "25.1.2"
firebaseAuth = "23.2.0"
play-services-location = "21.2.0"
yandex-mapkit = "4.7.0-full"
scenecore = "1.0.0-alpha03"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref ="play-services-location" }
yandex-mapkit = { group = "com.yandex.android", name = "maps.mobile", version.ref = "yandex-mapkit" }
scenecore = { group = "androidx.xr.scenecore", name = "scenecore", version.ref = "scenecore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

